version: "3.7"

services:
  tooljet-ai:
    image: ghcr.io/athulya-cloud/tooljet-ai-server:latest
    container_name: tooljet-ai
    ports:
      - "8080:8000"
    networks:
      - tooljet-network

  neo4j:
    image: neo4j:5
    container_name: tooljet-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/tooljet_secret
    volumes:
      - neo4j_data:/data
    networks:
      - tooljet-network

volumes:
  neo4j_data:

networks:
  tooljet-network:
    driver: bridge
