[supervisord]
nodaemon=true

[program:node-server]
command=node /app/server.js
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:ai-server]
command=python -m http.server %(ENV_AI_SERVER_PORT)s
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
