[supervisord]
nodaemon=true

[program:node-server]
command=node /app/server.js
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:ai-server]
command=python -m http.server 8000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:dummy-service]
command=python -m http.server 8001
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
